default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.27.9

images:
  -  quay.io/prometheus/prometheus:v2.27.1
  #- registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
