default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.27.9

images:
- registry.k8s.io/sig-storage/csi-attacher:v4.5.1
- registry.k8s.io/sig-storage/csi-resizer:v1.10.1
- registry.k8s.io/sig-storage/livenessprobe:v2.12.0
- registry.k8s.io/sig-storage/csi-provisioner:v4.0.1
- registry.k8s.io/sig-storage/csi-snapshotter:v7.0.2
- registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.1
- registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
- registry.k8s.io/csi-vsphere/driver:v3.3.0
- registry.k8s.io/csi-vsphere/syncer:v3.3.0
