default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.27.9

images:
  - docker.io/nginx:latest
  - docker.io/grafana/loki:3.1.1
  #- registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
