default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.27.9

images:
  - docker.io/nacos/nacos-server:v2.1.0
  #- registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
