default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.27.9

images:
  -  k8s.gcr.io/sig-storage/csi-attacher:v4.2.0
  -  k8s.gcr.io/sig-storage/csi-resizer:v1.7.0
  -  gcr.io/cloud-provider-vsphere/csi/release/driver:v3.0.0
  -  k8s.gcr.io/sig-storage/livenessprobe:v2.9.0
  -  gcr.io/cloud-provider-vsphere/csi/release/syncer:v3.0.0
  -  k8s.gcr.io/sig-storage/csi-provisioner:v3.4.0
  -  k8s.gcr.io/sig-storage/csi-snapshotter:v6.2.1
  -  k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.7.0
