default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.27.9

images:
  - docker.io/minio/minio:RELEASE.2023-03-24T21-41-23Z
  #- registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
