default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.27.9

images:
  - docker.io/mcr.microsoft.com/mssql/server:2022-latest
  #- registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
